# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
    # Enable version updates for pip
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
        interval: "weekly"
    - package-ecosystem: "pip"
      directory: "cdk/stacks/"
      schedule:
        interval: "weekly"
    - package-ecosystem: "pip"
      directory: "services/layers/frontend/python/lib/python3.11/site-packages"
      schedule:
        interval: "weekly"
